name: VoideriaYetkiliSure
version: 1.0.0
main: voideria.voiderialpc.VoideriaYetkiliSure
api-version: 1.21
folia-supported: true
commands:
  yetkilisure:
    description: Yetki süre sistemi komutları
    usage: /yetkilisure <ver|sil|liste|ekle|cikar|odulver|rapor|sifirla|yenile|yardim> [oyuncu] [rütbe/dakika]
    permission: voideria.yetkilisure.use
    aliases: [ysure, ys]
permissions:
  voideria.yetkilisure.admin:
    description: Yönetici yetkisi
    default: op
  voideria.yetkilisure.use:
    description: Temel komutlar
    default: op
  voideria.yetkilisure.reload:
    description: Plugin reload yetkisi
    default: op
libraries:
  - org.bstats:bstats-bukkit:3.0.2